### ISSUE TITLE
Getting error on deploy

### ISSUE THREAD

**Issue by aniketCyn** [tiagonnascimento/sfdx-orgdev-build-deploy#30]
=== deploy ===
Command executed: sfdx
With the following args: force:source:deploy,--wait,1,--manifest,manifest/package.xml,--targetusername,sfdc,--json,--testlevel,RunLocalTests
Having the following return: {
  "status": 1,
  "result": [
    {
      "error": "Unknown"
    }
  ],
  "name": "DeployFailed",
  "message": "Deploy failed.",
  "exitCode": 1,
  "actions": [],
  "commandName": "SourceDeployCommand",
  "data": [
    {
      "error": "Unknown"
    }
  ],
  "stack": "DeployFailed: Deploy failed.\n    at /usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceApiCommand.js:70:31\n    at async SourceDeployCommand.execLegacyCommand (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:29)\n    at async SourceDeployCommand.run (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/commands/force/source/deploy.js:32:16)\n    at async SourceDeployCommand._run (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)\n    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/sfdx/dist/cli.js:32:20)",
  "warnings": []
}

Error:  
Error: 

can you help me resolve this issue?

This is how i am using the action:

 - name: 'Build and Deploy'
              uses: tiagonnascimento/sfdx-orgdev-build-deploy@v2.1.1
              with:
                type: 'production'
                certificate_path: assets/server.key.enc
                decryption_key: ${{ secrets.DECRYPTION_KEY }}
                decryption_iv: ${{ secrets.DECRYPTION_IV }}
                client_id: ${{ secrets.CONSUMER_KEY }}
                username: ${{ secrets.USERNAME }}
                checkonly: false
                deploy_wait_time: '1'
                manifest_path: manifest/package.xml
                data_factory: scripts/apex/CreateBaseData.apex
                default_source_path: force-app/main/default

**Comment by tiagonnascimento** [comment]
Can you share the entire log?

**Comment by aniketCyn** [comment]
[logs_29.zip](https://github.com/tiagonnascimento/sfdx-orgdev-build-deploy/files/7882008/logs_29.zip)

**Comment by tiagonnascimento** [comment]
Hmmm

It looks fine looking at the log. This unknown error is not returned by the
action itself, instead it's returned by sfdx. Probably something is wrong
with your metadata but I can't point out exactly what it is, since the repo
is private. Did you look at Setup -> Deploy Status to see whether you can
get any idea from the sandbox?

**Comment by aniketCyn** [comment]
there is pr listed about having * in the class members it also showed me error for this also so i created the test classes  so may be the cause was due to my test class coverage
